export default {
  normalTerm : 416,
  // normalTerm : 2,
  quickTerm : 312,

  normalStartApproval : 65,
  quickStartApproval : 60,

  normalMinApproval : 35,
  quickMinApproval : 30,

  healthId : 1,
  defenceId : 2,
  agricultureId : 3,
  educationId : 4,

  healthInvst : 0,
  defenceInvst : 0,
  agricultureInvst : 0,
  educationInvst : 0,

  healthInfo : "Implement health policies to impact public health ",
  defenceInfo : "Implement defence policies to impact national security",
  agricultureInfo : "Implement agriculture policies to impact food production and reserves",
  educationInfo : "Implement education policies to impact national literacy",

  healthOp1 : 11,
  healthOp2 : 12,
  healthOp3 : 13,
  healthOp4 : 14,
  healthOp5 : 15,
  healthOp6 : 16,
  healthOp7 : 17,
  healthOp8 : 18,

  defenceOp1 : 21,
  defenceOp2 : 22,
  defenceOp3 : 23,
  defenceOp4 : 24,
  defenceOp5 : 25,
  defenceOp6 : 26,
  defenceOp7 : 27,
  defenceOp8 : 28,

  agricultureOp1 : 31,
  agricultureOp2 : 32,
  agricultureOp3 : 33,
  agricultureOp4 : 34,
  agricultureOp5 : 35,
  agricultureOp6 : 36,
  agricultureOp7 : 37,
  agricultureOp8 : 38,

  educationOp1 : 41,
  educationOp2 : 42,
  educationOp3 : 43,
  educationOp4 : 44,
  educationOp5 : 45,
  educationOp6 : 46,
  educationOp7 : 47,
  educationOp8 : 48,



  healthOp1Info : "Invest funds to vaccinate the public against polio, measles, mumps, diphtheria and influenza",
  healthOp2Info : "",
  healthOp3Info : "",
  healthOp4Info : "",
  healthOp5Info : "",
  healthOp6Info : "",
  healthOp7Info : "",
  healthOp8Info : "",

  defenceOp1Info : "",
  defenceOp2Info : "",
  defenceOp3Info : "",
  defenceOp4Info : "",
  defenceOp5Info : "",
  defenceOp6Info : "",
  defenceOp7Info : "",
  defenceOp8Info : "",

  agricultureOp1Info : "",
  agricultureOp2Info : "",
  agricultureOp3Info : "",
  agricultureOp4Info : "",
  agricultureOp5Info : "",
  agricultureOp6Info : "",
  agricultureOp7Info : "",
  agricultureOp8Info : "",

  educationOp1Info : "",
  educationOp2Info : "",
  educationOp3Info : "",
  educationOp4Info : "",
  educationOp5Info : "",
  educationOp6Info : "",
  educationOp7Info : "",
  educationOp8Info : "",




  healthOp1Label : "Vaccine - " ,
  healthOp2Label : "Mental Health - ",
  healthOp3Label : "Population Control - ",
  healthOp4Label : "Disease Control - ",
  healthOp5Label : "Medical Research - ",
  healthOp6Label : "New Mothers - ",
  healthOp7Label : "Disabled People - ",
  healthOp8Label : "Blood - ",

  defenceOp1Label : "Intelligence - ",
  defenceOp2Label : "Training - ",
  defenceOp3Label : "RnD - ",
  defenceOp4Label : "Safety Gear - ",
  defenceOp5Label : "Navy Equipment - ",
  defenceOp6Label : "Army Equipment - ",
  defenceOp7Label : "Airforce Equipment - ",
  defenceOp8Label : "Relief for Families - ",

  agricultureOp1Label : "Equipment - ",
  agricultureOp2Label : "Storage - ",
  agricultureOp3Label : "Irrigation - ",
  agricultureOp4Label : "Food Storage - ",
  agricultureOp5Label : "Agricultural loans - ",
  agricultureOp6Label : "Transportation - ",
  agricultureOp7Label : "Sustainable Agriculture - ",
  agricultureOp8Label : "Development - ",

  educationOp1Label : "Vernacular Language - ",
  educationOp2Label : "Vocational Education - ",
  educationOp3Label : "Government Schools - ",
  educationOp4Label : "College - ",
  educationOp5Label : "Affordable Education - ",
  educationOp6Label : "Teacher Pensions",
  educationOp7Label : "Teachers for the Disabled",
  educationOp8Label : "Training for teachers",


  healthOp1Cost : 12,
  healthOp2Cost : 6,
  healthOp3Cost : 5,
  healthOp4Cost : 5,
  healthOp5Cost : 6,
  healthOp6Cost : 8,
  healthOp7Cost : 17,
  healthOp8Cost : 9,

  defenceOp1Cost : 6,
  defenceOp2Cost : 3,
  defenceOp3Cost : 5,
  defenceOp4Cost : 2,
  defenceOp5Cost : 7,
  defenceOp6Cost : 5,
  defenceOp7Cost : 4,
  defenceOp8Cost : 13,

  agricultureOp1Cost : 5,
  agricultureOp2Cost : 3,
  agricultureOp3Cost : 4,
  agricultureOp4Cost : 15,
  agricultureOp5Cost : 6,
  agricultureOp6Cost : 12,
  agricultureOp7Cost : 5,
  agricultureOp8Cost : 7,

  educationOp1Cost : 11,
  educationOp2Cost : 4,
  educationOp3Cost : 8,
  educationOp4Cost : 13,
  educationOp5Cost : 7,
  educationOp6Cost : 5,
  educationOp7Cost : 4,
  educationOp8Cost : 9,

  timeOver: 1,
  approvalOver: 2,
  deptOver: 3,

  normalMinWinApproval : 50,
  quickMinWinApproval : 45,

}
