export default {
  normalTerm : 416,
  // normalTerm : 2,
  quickTerm : 312,

  normalStartApproval : 65,
  quickStartApproval : 60,

  normalMinApproval : 35,
  quickMinApproval : 30,

  healthId : 1,
  defenceId : 2,
  agricultureId : 3,
  educationId : 4,

  healthInvst : 0,
  defenceInvst : 0,
  agricultureInvst : 0,
  educationInvst : 0,

  healthInfo : "Implement health policies to impact public health ",
  defenceInfo : "Implement defence policies to impact national security",
  agricultureInfo : "Implement agriculture policies to impact food production and reserves",
  educationInfo : "Implement education policies to impact national literacy",

  healthOp1 : 11,
  healthOp2 : 12,
  healthOp3 : 13,
  healthOp4 : 14,
  healthOp5 : 15,
  healthOp6 : 16,
  healthOp7 : 17,
  healthOp8 : 18,

  defenceOp1 : 21,
  defenceOp2 : 22,
  defenceOp3 : 23,
  defenceOp4 : 24,
  defenceOp5 : 25,
  defenceOp6 : 26,
  defenceOp7 : 27,
  defenceOp8 : 28,

  agricultureOp1 : 31,
  agricultureOp2 : 32,
  agricultureOp3 : 33,
  agricultureOp4 : 34,
  agricultureOp5 : 35,
  agricultureOp6 : 36,
  agricultureOp7 : 37,
  agricultureOp8 : 38,

  educationOp1 : 41,
  educationOp2 : 42,
  educationOp3 : 43,
  educationOp4 : 44,
  educationOp5 : 45,
  educationOp6 : 46,
  educationOp7 : 47,
  educationOp8 : 48,



  healthOp1Info : "Vaccinate the public against polio, measles, mumps, diphtheria and influenza",
  healthOp2Info : "Spread awareness about mental health and to manage free centers of aid for mental disorders",
  healthOp3Info : "Make planned parenthood clinics available to the public and spread awareness about contraception and menstruation",
  healthOp4Info : "Invest funds to effectively monitor new diseases across the country and also control common ones like Dengue, Flu etc.",
  healthOp5Info : "Invest funds to increase medical research on various diseases and state of the art equipment",
  healthOp6Info : "Spread awareness for post natal care and also make safe and affordable delivery options for women available",
  healthOp7Info : "Make equipment needed by disabled people more easily available",
  healthOp8Info : "Invest funds to make collection, storage and transport of blood more efficient",

  defenceOp1Info : "Invest for counter-intelligence and counter-terrorism operations",
  defenceOp2Info : "Build better infrastructure and procure better equipment for training of soldiers",
  defenceOp3Info : "Invest funds to build state of the art equipments",
  defenceOp4Info : "Add better safety gear for soldiers",
  defenceOp5Info : "Add 7 Arihants, 4 Kievs, 1 Rajput and 2 Talwars",
  defenceOp6Info : "Add 1000 9M119 Svirs, 20 NAMICAs and 40 T-72 Ajeyas",
  defenceOp7Info : "Add 25 HAL Tejas and 10 Global 5000s",
  defenceOp8Info : "Allocate funds for the families of martyred soldiers",

  agricultureOp1Info : "Get better farming equipment and make them available to farmers at a cheaper price",
  agricultureOp2Info : "Build better storage facilities for food, fertilizers etc.",
  agricultureOp3Info : "Contruct better irrigation facilities in arid regions",
  agricultureOp4Info : "Implement better climate and monsoon tracking systems and convey the information to farmers",
  agricultureOp5Info : "Provide interest free loans schemes to farmers",
  agricultureOp6Info : "Get better transportation facilities for crops to minimize wastage",
  agricultureOp7Info : "Invest in research for sustainable agriculture practices",
  agricultureOp8Info : "Invest in research for better seed, fertilizer and equipment quality production",

  educationOp1Info : "Make education accessible to more people by promoting education in vernacular languages",
  educationOp2Info : "Increase the number of skilled labourers by promoting affordable and accessible vocational training",
  educationOp3Info : "Improve the infrastructure of government schools",
  educationOp4Info : "Make higher education accessible to more people",
  educationOp5Info : "Make education for all minors compulsory and provide them with free/affordable education",
  educationOp6Info : "Allocate funds for better salaries and pensions for teachers",
  educationOp7Info : "Train teachers catering towards disabled people",
  educationOp8Info : "Invest in training more teachers",




  healthOp1Label : "Vaccine - " ,
  healthOp2Label : "Mental Health - ",
  healthOp3Label : "Population Control - ",
  healthOp4Label : "Disease Control - ",
  healthOp5Label : "Medical Research - ",
  healthOp6Label : "New Mothers - ",
  healthOp7Label : "Disabled People - ",
  healthOp8Label : "Blood - ",

  defenceOp1Label : "Intelligence - ",
  defenceOp2Label : "Training - ",
  defenceOp3Label : "RnD - ",
  defenceOp4Label : "Safety Gear - ",
  defenceOp5Label : "Navy Equipment - ",
  defenceOp6Label : "Army Equipment - ",
  defenceOp7Label : "Airforce Equipment - ",
  defenceOp8Label : "Relief for Families - ",

  agricultureOp1Label : "Equipment - ",
  agricultureOp2Label : "Storage - ",
  agricultureOp3Label : "Irrigation - ",
  agricultureOp4Label : "Climate tracking - ",
  agricultureOp5Label : "Agricultural loans - ",
  agricultureOp6Label : "Transportation - ",
  agricultureOp7Label : "Sustainable Agriculture - ",
  agricultureOp8Label : "Development - ",

  educationOp1Label : "Vernacular Language - ",
  educationOp2Label : "Vocational Training - ",
  educationOp3Label : "Government Schools - ",
  educationOp4Label : "College - ",
  educationOp5Label : "Affordable Education - ",
  educationOp6Label : "Teacher Salary/Pension - ",
  educationOp7Label : "Teachers for the Disabled - ",
  educationOp8Label : "Training for teachers - ",

  healthOp1Cost : 12,
  healthOp2Cost : 6,
  healthOp3Cost : 5,
  healthOp4Cost : 5,
  healthOp5Cost : 6,
  healthOp6Cost : 8,
  healthOp7Cost : 17,
  healthOp8Cost : 9,

  defenceOp1Cost : 6,
  defenceOp2Cost : 3,
  defenceOp3Cost : 5,
  defenceOp4Cost : 2,
  defenceOp5Cost : 7,
  defenceOp6Cost : 5,
  defenceOp7Cost : 4,
  defenceOp8Cost : 13,

  agricultureOp1Cost : 5,
  agricultureOp2Cost : 3,
  agricultureOp3Cost : 4,
  agricultureOp4Cost : 15,
  agricultureOp5Cost : 6,
  agricultureOp6Cost : 12,
  agricultureOp7Cost : 5,
  agricultureOp8Cost : 7,

  educationOp1Cost : 11,
  educationOp2Cost : 4,
  educationOp3Cost : 8,
  educationOp4Cost : 13,
  educationOp5Cost : 7,
  educationOp6Cost : 5,
  educationOp7Cost : 4,
  educationOp8Cost : 9,

  timeOver: 1,
  approvalOver: 2,
  deptOver: 3,

  normalMinWinApproval : 50,
  quickMinWinApproval : 45,

}
